[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/pix"
  to = "/.netlify/functions/pix"
  status = 200

[[redirects]]
  from = "/api/produtos"
  to = "/.netlify/functions/produtos"
  status = 200
