[build]
  publish = "."
  functions = "netlify/functions"

<<<<<<< HEAD
[functions]
  node_bundler = "esbuild"

=======
[build.environment]
  NODE_VERSION = "22.12.0"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/techshop.html"
  status = 200
  force = true

>>>>>>> de5a94810f9dd0cfa1670a68e14af3efd4d80830
[[redirects]]
  from = "/api/pix"
  to = "/.netlify/functions/pix"
  status = 200
  force = true

[[redirects]]
  from = "/api/produtos"
  to = "/.netlify/functions/produtos"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
