[build]
  command = "node prepare-netlify.js"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express"]
  included_files = ["usuarios.json", "pedidos.json", "imagens/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
